# Generated by Django 4.2.8 on 2026-04-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Welcome to our company', max_length=120),
        ),
    ]
